### ISSUE TITLE
Terminar plan de sprint

### ISSUE THREAD

**Issue by IgnacioPlanasTh** [ISPP-Grupo7/Proyecto#48]
- Pasar a excel
	- Distribución estimado polivalente

**Comment by MatthewBL** [comment]
He sugerido algunas responsabilidades. Algunas de ellas son nuevas, como responsable de pruebas y de base de datos. Siento que hay muchas tareas sobre la responsabilidad de API, igual podríamos dividirlo en dos responsabilidades. De todas formas, todo esto es susceptible a cambio, es por tener algo de momento

**Comment by IgnacioPlanasTh** [comment]
> He sugerido algunas responsabilidades. Algunas de ellas son nuevas, como responsable de pruebas y de base de datos. Siento que hay muchas tareas sobre la responsabilidad de API, igual podríamos dividirlo en dos responsabilidades. De todas formas, todo esto es susceptible a cambio, es por tener algo de momento

Me parece guay meter esas responsabilidades, por mi lo hablamos coordinación
